## Second Movement: Exponential Defense with Geometric Attack Pattern

In [13]:
# Import required libraries
import networkx as nx
import numpy as np
from scipy.special import factorial
from datetime import datetime
import logging
from scipy.stats import geom
import sys
import os

In [14]:
import os

log_path = os.path.join(os.getcwd(), 'experiment_2.log')

if os.path.exists(log_path):
    os.remove(log_path)

logger = logging.getLogger()
handler = logging.FileHandler(log_path, mode='w')
handler.setFormatter(logging.Formatter('%(message)s'))
logger.addHandler(handler)
logger.setLevel(logging.INFO)

logger.info(f'[1] "experiment_2.log"')
logger.info(f'[1] "{datetime.now().strftime("%a %b %d %H:%M:%S %Y")}"')

In [15]:
%run attack_graph_MARA.ipynb

### Use Geometric Distribution

Geometric distribution models attacker behavior when defender checks randomly:
- High defense_rate -> attacker plays it safe, prefers fewer steps (steep dropoff)
- Low defense_rate -> attacker risks more steps (gradual decline)
- Key insight: probability p = defense_rate/(attack_rate + defense_rate) controls how 
  "risky" each additional step becomes

This fits our intuition: if attacker doesn't know WHEN checks happen (only how often),
they become more cautious - especially when defender checks frequently

<img src="images/GeometricDistr_DefenseRates.png" width="50%">

In [16]:
attack_rate_list = [3]  
defense_rate_list = [3]

# def random_steps(route, attack_rate=None, defense_rate=None):
#     length = len(route)
#     if attack_rate is None:
#         attack_rate = 2
#     if defense_rate is None:
#         defense_rate = 1
    
#     # Calculate p parameter for geometric distribution
#     p = defense_rate / (attack_rate + defense_rate)
#     # Ensure p is valid probability
#     p = max(p, np.finfo(float).eps)
    
#     # Get PMF for values 0 to length-1
#     pmf = geom.pmf(np.arange(1, length+1), p)
#     # Normalize (though geom.pmf should already sum to ~1)
#     pmf = pmf / pmf.sum()
#     return pmf

def random_steps(route, attack_rate=None, defense_rate=None, graph=None):
    """Geometric distribution for randomly moving defender"""
    p = defense_rate / (attack_rate + defense_rate)
    x = np.arange(len(route))
    pmf = p * np.power(1-p, x)
    pmf = pmf / pmf.sum()
    return pmf

In [17]:
#%run ctr-core_simple.ipynb
%run ctr-core_tests.ipynb
main()


=== Payoff Matrix ===

Rows (Defender locations): 2, 3, 4, 5, 7, 8

Columns (Attack paths): 1 -> 2 -> 3 -> 10 | 1 -> 2 -> 4 -> 10 | 1 -> 2 -> 5 -> 7 -> 8 -> 10

Matrix values:
[[5.5556 5.5556 9.0476]
 [0.     7.9365 9.5853]
 [7.9365 0.     9.5853]
 [7.9365 7.9365 7.9365]
 [7.9365 7.9365 5.5556]
 [7.9365 7.9365 0.    ]]


In [18]:
with open('experiment_2.log', 'r') as f:
    print(f.read())

[1] "experiment_2.log"
[1] "Sun Dec 22 10:04:56 2024"

++++++++++++++++++++++++++++++++

The virtual target nodeID is 10

attack rate =  3 , defense rate =  3 

	equilibrium for multiobjective security game (MOSG)

optimal defense strategy:
         prob.
2 0.000000e+00
3 2.927842e-01
4 2.927842e-01
5 0.000000e+00
7 0.000000e+00
8 4.144315e-01

worst case attack strategies per goal:
          1
1 0.3536079
2 0.3536079
3 0.2927842
[1] 0.056

Defender can keep attacker success below: 0.056
Attacker can guarantee success probability of: 0.056

